import { chromium } from "@playwright/test";
const out = "/tmp/claude-0/-home-user-BFNails/140ab651-3cc9-5ac3-84c6-94d81aa9da2e/scratchpad/shots";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push("console: " + m.text().slice(0, 200)); });
await page.goto("http://localhost:3000/catalogo/cherry-red", { waitUntil: "networkidle" });
await page.getByRole("button", { name: /^M Manos medianas/ }).click();
await page.getByRole("button", { name: "Agregar al carrito" }).click();
await page.goto("http://localhost:3000/catalogo/kitty-leopard", { waitUntil: "networkidle" });
await page.getByRole("button", { name: "Agregar al carrito" }).click();
await page.goto("http://localhost:3000/carrito", { waitUntil: "networkidle" });
await page.waitForTimeout(2600);
await page.screenshot({ path: `${out}/cart-receipt.png`, fullPage: true });
await page.goto("http://localhost:3000/checkout", { waitUntil: "networkidle" });
await page.fill("#name", "Mica Test"); await page.fill("#whatsapp", "11 5555 1234");
await page.getByRole("button", { name: /^Moto en zona/ }).click();
await page.fill("#street", "Av. Hipólito Yrigoyen 1234");
await page.getByRole("button", { name: /^Efectivo/ }).click();
await page.waitForTimeout(1800);
await page.screenshot({ path: `${out}/checkout-receipt.png`, fullPage: true });
await page.getByRole("button", { name: /Enviar pedido|Confirmar pedido/ }).click();
await page.waitForURL(/\/pedido\//, { timeout: 20000 });
await page.waitForLoadState("networkidle");
await page.waitForTimeout(2600);
await page.screenshot({ path: `${out}/order-receipt.png`, fullPage: true });
console.log("order:", page.url(), "errors:", errors.length); errors.slice(0, 5).forEach((e) => console.log("  ", e));
await browser.close();
