import { chromium } from "@playwright/test";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await page.goto("http://localhost:3000/disena", { waitUntil: "networkidle" });
await page.getByRole("button", { name: /^Coffin/ }).click();
await page.getByRole("button", { name: /^Bordó/ }).first().click();
await page.getByRole("button", { name: /^Francesita \+/ }).click();
await page.getByRole("button", { name: /Strass \(hasta/ }).click();
await page.waitForTimeout(900);
await page.locator("aside svg").first().screenshot({ path: "/tmp/claude-0/-home-user-BFNails/140ab651-3cc9-5ac3-84c6-94d81aa9da2e/scratchpad/shots/preview-a.png" });
await page.getByRole("button", { name: /^Almendra/ }).click();
await page.getByRole("button", { name: /^Nude/ }).first().click();
await page.getByRole("button", { name: /^Francesita \+/ }).click();
await page.getByRole("button", { name: /Strass \(hasta/ }).click();
await page.getByRole("button", { name: /Personajes/ }).click();
await page.getByRole("button", { name: /Animal print/ }).click();
await page.waitForTimeout(900);
await page.locator("aside svg").first().screenshot({ path: "/tmp/claude-0/-home-user-BFNails/140ab651-3cc9-5ac3-84c6-94d81aa9da2e/scratchpad/shots/preview-b.png" });
await browser.close();
